### ISSUE TITLE
The DATABASE is not set for the current session

### ISSUE THREAD

**Issue by subkumar349** [Snowflake-Labs/snowpark-extensions-py#15]
First of all I want to say thanks for this great module.
while using this module, it is throwing a strange error:
"The DATABASE is not set for the current session. To set this, either run session.sql("USE DATABASE").collect() or set the DATABASE connection property in the dict or properties file that you specify when creating a session"

Please look this error help me to fix this issue.

**Comment by orellabac** [comment]
Hi @subkumar349.
This might be an issue with the way you are creating the session. For example you can create it like:
```python
Session.builder.from_env().getOrCreate()
```

All available parameter coming from SNOW_xxx variables will be set, but it might be that the role does not have access to the provided database.

Another way to guarantee a database can be:

```python
Session.builder.from_env().config("database","db1").getOrCreate()
```
Please let us if this addresses your issue.

Thanks you very much for your feedback, and don't hesitate to enter more issues if needed

**Comment by sfc-gh-mrojas** [comment]
no more feedback. closing
