### ISSUE TITLE
applyInPandas doesn't support packages and imports

### ISSUE THREAD

**Issue by sfc-gh-jgriffith** [Snowflake-Labs/snowpark-extensions-py#30]
applyInPandas doesn't support using Snowpark Anaconda packages or imports, but these are available for use in UDTFs.

**Comment by sfc-gh-mrojas** [comment]
@sfc-gh-jgriffith this is good catch. We will work on that. I think that as a workaround you can just do session.add_import or session.add_package, that way those imports/packages will be added when the udf is pushed.

**Comment by sfc-gh-mrojas** [comment]
ApplyInPandas is now officially implemented in snowpark and this requirement is considered there
