### ISSUE TITLE
Issue with the PMML extension

### ISSUE THREAD

**Issue by VictorP10** [Snowflake-Labs/snowpark-extensions-py#35]
Hello 

We started testing the execution of the PMML model inside Snowflake. To do it we use the same JAVA function in this [repo](https://github.com/Snowflake-Labs/snowpark-extensions-py/tree/main/extras/pmml)

We were able to deploy the function but we witnessed a strange behaviour with the XGboost model.  Here is the summary of the behaviour: 

The PMML to Java file translation function is working.
The call to the generated function to execute the model is also successful (< 10s for 5000 executions).
For a linear model, the output results are correct.

However, for an XGBoost model, the output results are incorrect.
In the case of the XGBoost model, it was found that out of the 34 input parameters, only 12 of them are specified in the DataDictionary in the header of the PMML file. These are the only parameters that the model actually uses during its execution.

If we create the function with only the 12 parameters from the DataDictionary, it runs, and the output results are correct. Similarly, if we create the function with all 34 parameters but modify the call order so that the first 12 parameters called in the function correspond to the 12 parameters from the DataDictionary, the function runs, and the output results are also correct.

It would be much more convenient for the function to take all 34 parameters as input, in the order used during training, to ensure that it remains robust when retraining XGBoost models, without having to modify the PMML to Java translation script or the arguments of the model execution function.

The only solution I see is to automate, with Python for example, the UDF creation to take into account the parameters from the PMML files. Do you know any other path that we should investigate ?

**Comment by sfc-gh-mrojas** [comment]
We provided an UDF that handles this by using a variant for input / output
