### ISSUE TITLE
Repeated calls to `DataFrame::count` in the IPython Dataframe lead the query to be executed multiple times.

### ISSUE THREAD

**Issue by Taytay** [Snowflake-Labs/snowpark-extensions-py#40]
FIrst, thanks for this library. It's got some handy stuff!

I don't know if this bug is due to bad API design on the Dataframe more than anything, but there is a pretty dangerous, subtle bug. Every time you call `count` on a Snowpark Dataframe, it appears to re-execute the query. That's not exactly intuitive to me, but now I know to be scared of it, so maybe that's okay, but it does cause a problem in the Dataframe notebook display code:

https://github.com/Snowflake-Labs/snowpark-extensions-py/blob/0037623aafbd27e06b6f0bdb00065d22f7aeaa90/snowpark_extensions/dataframe_extensions.py#L40-L64

In there, here are the two scary lines:
```python
            count = self._cached_rowcount if hasattr(self,"_cached_rowcount") else self.count()
            self.count()
```

In the default case, every time a dataframe is _displayed_, count is called on it twice. Even if you cache the rowcount, it's called at least once. I was experimenting with dataframes in a notebook:

If you just run this python code like normal, it does what you expect, and inserts a single row with a value of '0' into TEST_TABLE:

```
session.sql("""
    DROP TABLE IF EXISTS TEST_TABLE 
""").collect()

session.sql("""
    CREATE TEMPORARY TABLE IF NOT EXISTS TEST_TABLE (
  counter INT)
""").collect()

insert_df = session.sql("""
    INSERT INTO TEST_TABLE(counter)
    SELECT COUNT(1) FROM TEST_TABLE
""")
insert_df.show()
```

But if you return that insert_df from a cell, that causes `display` to be called on it. If it's displayed, count is called (twice in my case), and two extra rows get inserted into my table.

The only reason `count` is being called right now is to look at the number of rows that are about to be displayed so that a warning can get displayed if fewer rows are displayed than expected. I don't know the dataframe api well enough, but perhaps there is a better way to accomplish this?

**Comment by orellabac** [comment]
Thanks for reporting this. This seems to have been a dummy error from my side. I just published version 0.0.41 that version should have this issue solved
